export const CategoryActionTypes = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',

  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_SUBCATEGORIES: 'SET_SUBCATEGORIES',
  SET_VARIATIONS: 'SET_VARIATIONS',

  GET_SUBCATEGORY: 'GET_SUBCATEGORY',
  SET_SUBCATEGORY: 'SET_SUBCATEGORY'
};
