export const ProductActionTypes = {
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

  PRODUCT_SEARCH_START: 'PRODUCT_SEARCH_START',
  PRODUCT_SET_SEARCH_RESULT: 'PRODUCT_SET_SEARCH_RESULT'
};
