export const StoreActionTypes = {
  FETCH_STORES_START: 'FETCH_STORES_START',
  FETCH_STORES_SUCCESS: 'FETCH_STORES_SUCCESS',
  FETCH_STORES_FAILURE: 'FETCH_STORES_FAILURE',

  FETCH_STORE: 'FETCH_STORE',
  SET_STORE: 'SET_STORE',
  CLEAN_STORE: 'CLEAN_STORE',
  FETCH_STORE_INFO: 'FETCH_STORE_INFO',
  SET_STORE_INFO: 'SET_STORE_INFO',
  CLEAN_STORE_INFO: 'CLEAN_STORE_INFO',

  STORE_SEARCH_START: 'STORE_SEARCH_START',
  STORE_SET_SEARCH_RESULT: 'STORE_SET_SEARCH_RESULT'
};
