export const UserActionTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  FETCH_USER: 'FETCH_USER',
  SET_USER: 'SET_USER',
  CLEAN_USER: 'CLEAN_USER',
  FETCH_USER_PROVIDER: 'FETCH_USER_PROVIDER',
  SET_USER_PROVIDER: 'SET_USER_PROVIDER',
  CLEAN_USER_PROVIDER: 'CLEAN_USER_PROVIDER',

  USER_SEARCH_START: 'USER_SEARCH_START',
  USER_SET_SEARCH_RESULT: 'USER_SET_SEARCH_RESULT'
};
